export const topics = [
  "Data Distribution Strategies",
  "Data Partitioning",
  "Data Replication",
  "Data Consistency Models",
  "Distributed Databases: Concepts and Terminology",
  "CAP Theorem",
  "Distributed Consensus Algorithms",
  "Paxos",
  "Raft",
  "Leader Election Algorithms",
  "Distributed Transactions",
  "Two-Phase Commit (2PC)",
  "Distributed Queues",
  "Apache Kafka",
  "Redis",
  "Message Queues",
  "NoSQL Databases",
  "MongoDB",
  "Cassandra",
  "HBase",
  "Cloud-Based Data Stores",
  "Amazon DynamoDB",
  "Google Cloud Spanner",
  "Azure Cosmos DB",
  "Distributed File Systems",
  "Hadoop Distributed File System (HDFS)",
  "Apache Cassandra",
  "Data Consistency and Fault Tolerance",
  "Distributed Data Backup and Recovery",
  "Data Security and Encryption in Distributed Systems",
  "Data Governance and Compliance in Distributed Environments",
  "Performance Optimization in Distributed Data Storage",
  "Data Analytics and Processing in Distributed Systems",
  "Apache Spark",
  "Apache Flink",
  "Data Integration and ETL in Distributed Systems",
  "Distributed Data Visualization and Reporting",
  "Emerging Trends in Distributed Data Storage"
]

